In [8]:
with open("midas-open_uk-daily-temperature-obs_dv-201901_berkshire_00832_reading-university_qcv-0_1960.csv", "r") as f:
    lines = f.readlines()


print(lines[:30])

['Conventions,G,BADC-CSV,1\n', 'title,G,uk-daily-temperature-obs\n', 'source,G,Met Office MIDAS database\n', 'creator,G,Met Office\n', 'activity,G,Met Office MIDAS Open: UK Land Surface Stations Data\n', 'feature_type,G,point series\n', 'collection_name,G,midas-open\n', 'collection_version_number,G,dataset-version-201901\n', 'history,G,Created 2019-01-29\n', 'last_revised_date,G,2019-01-29\n', 'observation_station,G,reading-university\n', 'historic_county_name,G,berkshire\n', 'midas_station_id,G,00832\n', 'location,G,51.45,-0.962\n', 'height,G,45,m\n', 'date_valid,G,1960-01-01 00:00:00,1960-12-31 23:59:59\n', 'midas_qc_version_number,G,0\n', 'comments,G,The midas_qc_version_number indicates if the data are original received message (0) or current best version (1)\n', 'comments,G,This file contains station observations\n', 'comments,G,missing values are identified with the missing data flag\n', 'missing_value,G,NA\n', 'coordinate_variable,ob_end_time,t\n', 'long_name,ob_end_time,Date and time at end of observation,s\n', 'type,ob_end_time,char\n', 'comments,ob_end_time,Date and time (YYYY-MM-DD HH:MM:SS) at the end of the observation period\n', 'comments,ob_end_time,Use ob_end_time in conjunction with ob_hour_count to determine the period over which the observation relates.\n', 'comments,ob_end_time,Common periods include 12 hour observations ending at 0900 or 2100 or 24 hour observations ending at 0900.\n', 'long_name,id_type,identifier type,1\n', 'type,id_type,char\n', 'comments,id_type,a station may have more than one id assigned to it defined by id_type\n']

In [19]:
for i, line in enumerate(lines):
    if line.strip() == 'data':
        print(i)

print(lines[90: 91])

89
['ob_end_time,id_type,id,ob_hour_count,version_num,met_domain_name,src_id,rec_st_ind,max_air_temp,min_air_temp,min_grss_temp,min_conc_temp,max_air_temp_q,min_air_temp_q,min_grss_temp_q,min_conc_temp_q,max_air_temp_j,min_air_temp_j,min_grss_temp_j,min_conc_temp_j,meto_stmp_time,midas_stmp_etime\n']

In [62]:
import pandas as pd

observations_temp_data = pd.read_csv("midas-open_uk-daily-temperature-obs_dv-201901_berkshire_00832_reading-university_qcv-0_1960.csv", skiprows=90)

In [63]:
observations_temp_data

,ob_end_time,id_type,id,ob_hour_count,version_num,met_domain_name,src_id,rec_st_ind,max_air_temp,min_air_temp,...,max_air_temp_q,min_air_temp_q,min_grss_temp_q,min_conc_temp_q,max_air_temp_j,min_air_temp_j,min_grss_temp_j,min_conc_temp_j,meto_stmp_time,midas_stmp_etime
0,1960-01-14 09:00:00,DCNN,5578.0,24.0,0.0,DLY3208,832.0,1012.0,-1.1,-4.4,...,9.0,109.0,109.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN
1,end data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [65]:
observations_temp_data = observations_temp_data[observations_temp_data['ob_end_time'] != 'end data']
observation_cols = ['id', 'ob_end_time', 'max_air_temp', 'max_air_temp_q', 'min_air_temp', 'min_air_temp_q']
observations_temp_data = observations_temp_data[observation_cols]


observations_temp_data

,id,ob_end_time,max_air_temp,max_air_temp_q,min_air_temp,min_air_temp_q
0,5578.0,1960-01-14 09:00:00,-1.1,9.0,-4.4,109.0

In [71]:
with open('midas-open_uk-daily-temperature-obs_dv-202507_station-metadata.csv') as f:
    meta_data_lines = f.readlines()



print(meta_data_lines)

['Conventions,G,BADC-CSV,1\n', 'title,G,Midas-open: Station site metadata for uk-daily-temperature-obs\n', 'source,G,Met Office MIDAS database\n', 'creator,G,Met Office\n', 'activity,G,Met Office MIDAS Open: UK Land Surface Stations Data\n', 'feature_type,G,point collection\n', 'observation_station,G,UK land surface observing network\n', 'location,G,UK\n', 'collection_name,G,midas-open\n', 'collection_version_number,G,dataset-version-202507\n', 'date_valid,G,2025-06-24\n', 'history,G,Created 2025-06-24\n', 'last_revised_date,G,2025-06-24\n', 'comments,G,This file contains geographic and temporal information for the stations covered in this version of the uk-daily-temperature-obs part of the MIDAS-open collection\n', 'comments,G,The temporal range given here is in relation to the data temporal range available for this station within this dataset and may differ from other dates for the given station in other MIDAS-open datasets\n', 'comments,G,The geographic location relates to the currently recorded station location to 3 decimal places of latitude and longitude\n', 'comments,G,If more precise geographical location information is required please contact the Met Office directly as there may be data management restrictions for stations located on private property\n', 'comments,G,Further station-specific details are given in each station folder in the associated capability files\n', 'comments,G,For fuller station metadata please use the MIDAS station search tool available from the Centre for Environmental Data Analysis\n', 'coordinate_variable,src_id,x\n', 'long_name,src_id,The unique MIDAS identifier for the station,1\n', 'type,src_id,int\n', 'comments,src_id,This is a unique ID ascribed to this station within the MIDAS system. It is used across MIDAS as a way to join related data and metadata together where a site may have used different identifiers for different meteorological reports over time.\n', 'long_name,station_name,The name for this station,1\n', 'type,station_name,char\n', 'long_name,station_file_name,The filename used for this station,1\n', 'type,station_file_name,char\n', 'comments,station_file_name,The filename is derived from the station name but replacing spaces with - as necessary\n', 'long_name,historic_county,the historic county this station is within,1\n', 'type,historic_county,char\n', 'comments,historic_county,Within MIDAS stations are associated with a set of fixed historic county definitions for the UK and are not amended to reflect modern county boundary changes. For more details refer to the MIDAS documentation.\n', 'long_name,authority,The current authority in charge of MIDAS station,1\n', 'type,authority,char\n', 'long_name,station_latitude,The station latitude (WGS84),degrees\n', 'type,station_latitude,float\n', 'long_name,station_longitude,The station longitude (WGS84),degrees\n', 'type,station_longitude,float\n', 'long_name,station_elevation,The station elevation,m\n', 'type,station_elevation,float\n', 'comments,station_elevation,The station elevation in metres above mean sea level\n', 'long_name,first_year,first year of data associated with this station in this dataset,year\n', 'type,first_year,float\n', 'comments,first_year,This relates to the first year of available data within this version of this dataset. The first year may differ for this station within other datasets of Midas-open\n', 'long_name,last_year,last year of data associated with this station in this dataset,year\n', 'type,last_year,float\n', 'comments,last_year,This relates to the last year of data associated with this station in this dataset. It does not indicate whether the station is currently operational and the last year may differ for this station within other datasets of Midas-open\n', 'comments,last_year,The first and last year indicate simply the year of first and last available data in this dataset. They do not indicate the availability of data between those dates or availability of data within other datasets of Midas-open\n', 'data\n', 'src_id,station_name,station_file_name,historic_county,authority,station_latitude,station_longitude,station_elevation,first_year,last_year\n', '00001,FOULA,foula,shetland,Met Office,60.154,-2.074,22,1985,2003\n', '00003,FAIR ISLE,fair-isle,shetland,Met Office,59.526,-1.63,57,1974,2024\n', '00004,SUMBURGH,sumburgh,shetland,Met Office,59.879,-1.299,7,1978,1996\n', '00005,HAMNAVOE,hamnavoe,shetland,Met Office,60.104,-1.333,21,1962,1973\n', '00006,SCATSTA,scatsta,shetland,Met Office,60.439,-1.308,15,1979,1980\n', '00009,LERWICK,lerwick,shetland,Met Office,60.139,-1.185,82,1921,2024\n', '00010,SELLA NESS,sella-ness,shetland,Met Office,60.447,-1.278,7,1990,2004\n', '00012,BALTASOUND NO 2,baltasound-no-2,shetland,Met Office,60.748,-0.856,15,1992,2024\n', '00013,BALTASOUND,baltasound,shetland,Met Office,60.759,-0.888,24,1914,1995\n', '00017,SULE SKERRY,sule-skerry,orkney,Met Office,59.082,-4.405,12,1957,1974\n', '00019,RACKWICK,rackwick,orkney,Met Office,58.873,-3.387,18,1987,2008\n', '00020,STENNESS,stenness,orkney,Met Office,58.982,-3.223,23,1961,1975\n', '00021,EVIE,evie,orkney,Met Office,59.105,-3.088,34,1965,1967\n', '00022,COSTA,costa,orkney,Met Office,59.131,-3.148,35,1961,1964\n', '00023,KIRKWALL,kirkwall,orkney,Met Office,58.953,-2.901,26,1957,2024\n', '00024,WEYLAND,weyland,orkney,Met Office,58.986,-2.948,24,1977,1980\n', '00025,"NORTH RONALDSAY, GERBO",north-ronaldsay-gerbo,orkney,Met Office,59.361,-2.415,11,1994,1997\n', '00026,DOUNREAY,dounreay,caithness,Met Office,58.579,-3.739,21,1959,1983\n', '00028,"BERRIEDALE, LANGWELL",berriedale-langwell,caithness,Met Office,58.18,-3.53,67,1981,1985\n', '00029,"HALKIRK , OLGRINBERG",halkirk-olgrinberg,caithness,Met Office,58.453,-3.559,71,1959,1961\n', '00031,LYBSTER,lybster,caithness,Met Office,58.311,-3.285,85,1994,2003\n', '00032,WICK AIRPORT,wick-airport,caithness,Met Office,58.454,-3.09,36,1930,2024\n', '00033,KEISS,keiss,caithness,Met Office,58.542,-3.11,30,1972,1986\n', '00034,JOHN O GROATS,john-o-groats,caithness,Met Office,58.635,-3.064,30,1968,1972\n', '00035,GEISGEIL,geisgeil,sutherland,Met Office,58.319,-5.126,12,1978,1980\n', '00036,DUARTMORE BRIDGE,duartmore-bridge,sutherland,Met Office,58.289,-5.072,30,1980,2004\n', '00037,CAPE WRATH,cape-wrath,sutherland,Met Office,58.625,-5.0,112,1957,1997\n', '00038,ACHFARY,achfary,sutherland,Met Office,58.311,-4.916,46,2006,2024\n', '00039,ACHANY NO 2,achany-no-2,sutherland,Met Office,57.981,-4.427,107,1977,1983\n', '00040,CASSLEY,cassley,sutherland,Met Office,58.168,-4.727,99,1974,2024\n', '00042,ACHANY,achany,sutherland,Met Office,57.982,-4.422,85,1959,1971\n', '00043,LAIRG NO 2,lairg-no-2,sutherland,Met Office,58.019,-4.407,91,1971,2000\n', '00044,ALTNAHARRA NO 2,altnaharra-no-2,sutherland,Met Office,58.288,-4.442,81,1993,2024\n', '00045,TORRISDALE,torrisdale,sutherland,Met Office,58.523,-4.273,27,1977,1991\n', '00046,STRATHY 1,strathy-1,sutherland,Met Office,58.52,-4.01,38,1959,1976\n', '00048,"KINBRACE, HATCHERY",kinbrace-hatchery,sutherland,Met Office,58.23,-3.922,103,1979,2024\n', '00049,ACHENTOUL NO 2,achentoul-no-2,sutherland,Met Office,58.293,-3.924,137,1967,1971\n', '00050,STRATHY EAST,strathy-east,sutherland,Met Office,58.561,-3.992,68,1993,2024\n', '00051,KNEEP,kneep,western-isles,Met Office,58.222,-6.948,5,1983,1988\n', '00052,AULTBEA NO 2,aultbea-no-2,ross-and-cromarty,Met Office,57.859,-5.633,11,1990,2024\n', '00054,STORNOWAY AIRPORT,stornoway-airport,western-isles,Met Office,58.213,-6.319,15,1873,2024\n', '00055,BUTT OF LEWIS,butt-of-lewis,western-isles,Met Office,58.516,-6.262,16,1984,1995\n', '00056,BALMACARA HOUSE,balmacara-house,ross-and-cromarty,Met Office,57.286,-5.652,4,1963,1978\n', '00058,DIABAIG,diabaig,ross-and-cromarty,Met Office,57.579,-5.692,60,1977,2010\n', '00059,GLEN TORRIDON,glen-torridon,ross-and-cromarty,Met Office,57.551,-5.46,55,1968,1971\n', '00060,POOLEWE,poolewe,ross-and-cromarty,Met Office,57.775,-5.598,6,1963,2024\n', '00061,RUDH RE,rudh-re,ross-and-cromarty,Met Office,57.858,-5.813,16,1965,1977\n', '00062,"ACHNASHELLACH, LAIR",achnashellach-lair,ross-and-cromarty,Met Office,57.484,-5.32,40,1982,1984\n', '00063,INVERPOLLY,inverpolly,ross-and-cromarty,Met Office,58.068,-5.267,14,1963,1998\n', '00064,PLOCKTON,plockton,ross-and-cromarty,Met Office,57.337,-5.653,12,1979,2019\n', '00065,ACHNASHELLACH,achnashellach,ross-and-cromarty,Met Office,57.49,-5.275,67,1926,1982\n', '00066,KINLOCHEWE,kinlochewe,ross-and-cromarty,Met Office,57.613,-5.306,25,1953,2024\n', '00067,LOCH GLASCARNOCH,loch-glascarnoch,ross-and-cromarty,Met Office,57.725,-4.895,269,1992,2024\n', '00068,KNOCKANROCK,knockanrock,ross-and-cromarty,Met Office,58.031,-5.072,244,1968,1998\n', '00069,CLUANIE INN,cluanie-inn,ross-and-cromarty,Met Office,57.156,-5.181,223,1994,1996\n', '00070,STRATHCONON,strathconon,ross-and-cromarty,Met Office,57.555,-4.794,107,1968,1981\n', '00071,CRAIGDARROCH,craigdarroch,ross-and-cromarty,Met Office,57.578,-4.607,38,1973,1979\n', '00072,CONTIN,contin,ross-and-cromarty,Met Office,57.575,-4.587,29,1972,1975\n', '00074,DINGWALL,dingwall,ross-and-cromarty,Met Office,57.6,-4.447,7,1983,2006\n', '00075,CRANNICH,crannich,ross-and-cromarty,Met Office,57.752,-4.272,197,1985,1989\n', '00076,FORTROSE,fortrose,ross-and-cromarty,Met Office,57.574,-4.093,5,1926,1995\n', '00077,INVERGORDON HARBOUR,invergordon-harbour,ross-and-cromarty,Met Office,57.687,-4.167,3,1989,2001\n', '00078,INVERGORDON,invergordon,ross-and-cromarty,Met Office,57.703,-4.158,15,1979,1982\n', '00079,TAIN RANGE,tain-range,ross-and-cromarty,Met Office,57.819,-3.967,4,1994,2024\n', '00080,TARBATNESS,tarbatness,ross-and-cromarty,Met Office,57.865,-3.776,18,1968,1985\n', '00081,ST KILDA,st-kilda,western-isles,Met Office,57.811,-8.564,30,1982,1988\n', '00082,BARRA (W I),barra-w-i,western-isles,Met Office,57.025,-7.449,3,1997,2007\n', '00083,LOCHBOISDALE,lochboisdale,western-isles,Met Office,57.155,-7.316,6,1990,2003\n', '00084,BENBECULA AIRPORT,benbecula-airport,western-isles,Met Office,57.475,-7.371,6,1957,1996\n', '00085,SCALPAY,scalpay,western-isles,Met Office,57.872,-6.699,18,1979,1995\n', '00086,NEIST POINT,neist-point,inverness-shire,Met Office,57.423,-6.788,21,1983,1989\n', '00087,WATERSTEIN,waterstein,inverness-shire,Met Office,57.436,-6.769,83,1990,2004\n', '00089,RHUM: KINLOCH,rhum-kinloch,inverness-shire,Met Office,57.014,-6.282,5,1959,2009\n', '00090,SKYE: PRABOST,skye-prabost,inverness-shire,Met Office,57.467,-6.305,67,1959,1989\n', '00092,INVERAILORT,inverailort,inverness-shire,Met Office,56.872,-5.67,2,1982,2015\n', '00093,HEASTE,heaste,inverness-shire,Met Office,57.189,-5.894,100,1974,1984\n', '00094,BROADFORD:ISLE OF SKYE,broadford-isle-of-skye,inverness-shire,Met Office,57.239,-5.895,8,1988,1991\n', '00095,EILANREACH,eilanreach,inverness-shire,Met Office,57.199,-5.63,8,1982,2004\n', '00096,ONICH,onich,inverness-shire,Met Office,56.72,-5.224,15,1926,1995\n', '00097,FORT WILLIAM NO 4,fort-william-no-4,inverness-shire,Met Office,56.829,-5.076,20,1984,1993\n', '00098,FORT WILLIAM,fort-william,inverness-shire,Met Office,56.809,-5.125,11,1959,1960\n', '00099,FORT WILLIAM NO 3,fort-william-no-3,inverness-shire,Met Office,56.837,-5.078,8,1960,1971\n', '00101,CORPACH,corpach,inverness-shire,Met Office,56.839,-5.149,8,1967,1980\n', '00102,KILTARLITY,kiltarlity,inverness-shire,Met Office,57.427,-4.497,75,1985,2011\n', '00103,AONACH MOR,aonach-mor,inverness-shire,Met Office,56.822,-4.969,1130,1992,2024\n', '00104,LOCH OICH,loch-oich,inverness-shire,Met Office,57.044,-4.799,37,1975,1977\n', '00105,TULLOCH BRIDGE,tulloch-bridge,inverness-shire,Met Office,56.867,-4.708,249,1990,2024\n', '00107,FORT AUGUSTUS,fort-augustus,inverness-shire,Met Office,57.144,-4.677,21,1914,1997\n', '00109,CANNICH,cannich,inverness-shire,Met Office,57.292,-4.828,107,1959,1967\n', '00110,LENTRAN,lentran,inverness-shire,Met Office,57.459,-4.373,146,1975,2024\n', '00111,DALWHINNIE NO 2,dalwhinnie-no-2,inverness-shire,Met Office,56.94,-4.238,351,1973,2024\n', '00112,LAGGANLIA,lagganlia,inverness-shire,Met Office,57.111,-3.891,250,1971,1987\n', '00113,AVIEMORE,aviemore,inverness-shire,Met Office,57.206,-3.828,228,1982,2024\n', '00114,DRUMNADROCHIT,drumnadrochit,inverness-shire,Met Office,57.328,-4.486,53,1990,2024\n', '00115,INVERNESS,inverness,inverness-shire,Met Office,57.486,-4.222,4,1957,2015\n', '00116,DALCROSS,dalcross,inverness-shire,Met Office,57.542,-4.062,11,1977,1994\n', '00117,CAIRNGORM SUMMIT,cairngorm-summit,inverness-shire,Met Office,57.116,-3.643,1237,1992,2024\n', '00118,CAIRNGORM CHAIRLIFT,cairngorm-chairlift,inverness-shire,Met Office,57.133,-3.669,663,1980,2024\n', '00121,ACHNAGOICHAN,achnagoichan,inverness-shire,Met Office,57.152,-3.798,305,1960,1975\n', '00122,GLENMORE LODGE,glenmore-lodge,inverness-shire,Met Office,57.164,-3.678,337,1961,1980\n', '00123,TOMATIN,tomatin,inverness-shire,Met Office,57.339,-4.007,311,1973,1992\n', '00124,MOY,moy,inverness-shire,Met Office,57.381,-4.056,305,1969,1971\n', '00125,"TOMATIN, FREEBURN",tomatin-freeburn,inverness-shire,Met Office,57.345,-4.003,290,1993,2002\n', '00126,NAIRN,nairn,nairnshire,Met Office,57.587,-3.893,8,1931,1998\n', '00127,FORRES NO 2,forres-no-2,moray-in-grampian-region,Met Office,57.615,-3.61,5,1976,2002\n', '00128,"GRANTOWN-ON-SPEY, GRAMMAR SCHOOL",grantown-on-spey-grammar-school,moray-in-highland-region,Met Office,57.334,-3.6,218,1993,2000\n', '00129,"GRANTOWN-ON-SPEY, MONIACK",grantown-on-spey-moniack,moray-in-highland-region,Met Office,57.327,-3.616,219,1959,1962\n', '00130,GRANTOWN-ON-SPEY,grantown-on-spey,moray-in-highland-region,Met Office,57.335,-3.606,220,1966,2007\n', '00131,FORRES,forres,moray-in-grampian-region,Met Office,57.608,-3.597,50,1959,1976\n', '00132,KINLOSS,kinloss,moray-in-grampian-region,Met Office,57.645,-3.563,5,1957,2024\n', '00133,ALDROUGHTY,aldroughty,moray-in-grampian-region,Met Office,57.645,-3.379,30,1982,2000\n', '00134,ROTHES,rothes,moray-in-grampian-region,Met Office,57.532,-3.196,61,1982,1995\n', '00135,ELGIN,elgin,moray-in-grampian-region,Met Office,57.639,-3.298,28,1959,1965\n', '00136,ELGIN NO 2,elgin-no-2,moray-in-grampian-region,Met Office,57.65,-3.293,15,1965,1982\n', '00137,LOSSIEMOUTH,lossiemouth,moray-in-grampian-region,Met Office,57.711,-3.323,7,1959,2024\n', '00138,GORDON CASTLE,gordon-castle,banffshire,Met Office,57.621,-3.09,32,1879,1975\n', '00139,CLASHNOIR,clashnoir,banffshire,Met Office,57.282,-3.287,338,1977,1981\n', '00140,GLENLIVET,glenlivet,banffshire,Met Office,57.354,-3.345,213,1963,2008\n', '00141,KEITH,keith,banffshire,Met Office,57.553,-2.949,106,1973,1996\n', '00142,"BANFF, GOLF CLUB",banff-golf-club,banffshire,Met Office,57.661,-2.521,15,1989,2024\n', '00143,BANFF NO 2,banff-no-2,banffshire,Met Office,57.671,-2.523,24,1960,1988\n', '00144,"CORGARFF, CASTLE LODGE",corgarff-castle-lodge,aberdeenshire,Met Office,57.165,-3.23,400,1994,2002\n', '00145,CAIRNWELL,cairnwell,aberdeenshire,Met Office,56.879,-3.421,928,1994,2024\n', '00147,BRAEMAR,braemar,aberdeenshire,Met Office,57.006,-3.398,339,1857,2005\n', '00148,BALMORAL,balmoral,aberdeenshire,Met Office,57.037,-3.22,283,1918,2024\n', '00149,BALLATER FIELD CENTRE,ballater-field-centre,aberdeenshire,Met Office,57.047,-3.043,200,1989,1999\n', '00150,ABOYNE NO 2,aboyne-no-2,aberdeenshire,Met Office,57.076,-2.841,140,1994,2024\n', '00151,DINNET,dinnet,aberdeenshire,Met Office,57.109,-2.916,177,1962,1982\n', '00152,LOGIE COLDSTONE,logie-coldstone,aberdeenshire,Met Office,57.127,-2.937,185,1959,1962\n', '00153,FINZEAN,finzean,kincardineshire,Met Office,57.016,-2.67,133,1982,1988\n', '00154,ALFORD NO 2,alford-no-2,aberdeenshire,Met Office,57.24,-2.686,137,1982,1983\n', '00155,LEITH HALL,leith-hall,aberdeenshire,Met Office,57.356,-2.766,180,1987,2000\n', '00156,GARTLY,gartly,aberdeenshire,Met Office,57.379,-2.795,146,1968,1987\n', '00157,HUNTLY,huntly,aberdeenshire,Met Office,57.45,-2.786,122,1959,1966\n', '00158,INVERURIE NO 2,inverurie-no-2,aberdeenshire,Met Office,57.274,-2.368,54,1967,1992\n', '00159,FYVIE CASTLE,fyvie-castle,aberdeenshire,Met Office,57.443,-2.39,55,1959,2024\n', '00160,CRAIBSTONE,craibstone,aberdeenshire,Met Office,57.187,-2.215,102,1931,2021\n', '00161,DYCE,dyce,aberdeenshire,Met Office,57.205,-2.205,65,1957,2024\n', '00163,"ABERDEEN, MANNOFIELD RESR",aberdeen-mannofield-resr,aberdeenshire,Met Office,57.128,-2.14,52,1959,2008\n', '00164,HILTON (ABERDEENSHIRE),hilton-aberdeenshire,aberdeenshire,Met Office,57.165,-2.129,70,1963,1965\n', '00165,UDNY,udny,aberdeenshire,Met Office,57.299,-2.158,107,1960,1968\n', '00166,FRASERBURGH,fraserburgh,aberdeenshire,Met Office,57.697,-2.003,18,1967,1987\n', '00167,CULTERTY NO 2,culterty-no-2,aberdeenshire,Met Office,57.325,-2.003,3,1974,1999\n', '00168,FOREHILL,forehill,aberdeenshire,Met Office,57.506,-1.844,41,1977,2010\n', '00169,RATTRAY HEAD,rattray-head,aberdeenshire,Met Office,57.614,-1.846,26,1957,1968\n', '00173,INCHMARLO,inchmarlo,kincardineshire,Met Office,57.06,-2.542,80,1990,2005\n', '00174,STRACHAN,strachan,kincardineshire,Met Office,57.015,-2.502,120,1962,1972\n', '00175,BANCHORY,banchory,kincardineshire,Met Office,57.053,-2.509,94,1967,1982\n', '00176,DURRIS,durris,kincardineshire,Met Office,57.032,-2.404,107,1988,2024\n', '00177,INVERBERVIE NO 2,inverbervie-no-2,kincardineshire,Met Office,56.852,-2.266,134,1992,2024\n', '00178,STONEHAVEN,stonehaven,kincardineshire,Met Office,56.969,-2.207,4,1959,1985\n', '00179,STONEHAVEN NO 2,stonehaven-no-2,kincardineshire,Met Office,56.946,-2.212,85,1985,2000\n', '00180,MUCHALLS,muchalls,kincardineshire,Met Office,57.018,-2.17,64,1959,1966\n', '00181,MYLNEFIELD,mylnefield,angus,Met Office,56.456,-3.07,26,1954,2024\n', '00182,AUCHTERHOUSE,auchterhouse,angus,Met Office,56.538,-3.063,232,1959,1965\n', '00183,DUNDEE,dundee,angus,Met Office,56.47,-2.94,45,1959,1996\n', '00184,GLAMIS CASTLE NO 2,glamis-castle-no-2,angus,Met Office,56.625,-3.0,62,1959,1973\n', '00185,FORFAR NO 3,forfar-no-3,angus,Met Office,56.683,-2.929,91,1985,1994\n', '00186,FORFAR NO 2,forfar-no-2,angus,Met Office,56.657,-2.775,67,1981,1983\n', '00187,WHITEHILLOCKS,whitehillocks,angus,Met Office,56.906,-2.907,258,1962,2013\n', '00188,BUDDON NESS,buddon-ness,angus,Met Office,56.468,-2.75,5,1959,1973\n', '00189,CARNOUSTIE NO 2,carnoustie-no-2,angus,Met Office,56.507,-2.725,27,1959,1977\n', '00191,ARBROATH,arbroath,angus,Met Office,56.561,-2.573,29,1914,1994\n', '00192,USAN,usan,angus,Met Office,56.681,-2.452,47,1965,1979\n', '00193,MONTROSE,montrose,angus,Met Office,56.746,-2.481,55,1959,1992\n', '00194,CRIANLARICH,crianlarich,perthshire-in-central-region,Met Office,56.419,-4.659,174,1975,1975\n', '00195,TYNDRUM NO 3,tyndrum-no-3,perthshire-in-central-region,Met Office,56.419,-4.661,168,1990,2024\n', '00196,LOCH RANNOCH POWER HOUSE,loch-rannoch-power-house,perthshire-in-tayside-region,Met Office,56.693,-4.401,206,1999,2005\n', '00197,ABERFOYLE,aberfoyle,perthshire-in-central-region,Met Office,56.174,-4.369,28,1968,2001\n', '00199,LOCH VENACHAR,loch-venachar,perthshire-in-central-region,Met Office,56.23,-4.263,84,1982,2006\n', '00200,STRATHYRE,strathyre,perthshire-in-central-region,Met Office,56.321,-4.328,130,1959,1967\n', '00201,BALQUHIDDER NO 2,balquhidder-no-2,perthshire-in-central-region,Met Office,56.355,-4.397,136,1982,1992\n', '00202,KILLIN,killin,perthshire-in-central-region,Met Office,56.484,-4.363,116,1984,1989\n', '00203,CALLANDER,callander,perthshire-in-central-region,Met Office,56.242,-4.217,70,1960,1965\n', '00204,CALLANDER NO 2,callander-no-2,perthshire-in-central-region,Met Office,56.245,-4.206,107,1968,1982\n', '00205,ARDTALNAIG,ardtalnaig,perthshire-in-tayside-region,Met Office,56.528,-4.112,130,1959,2017\n', '00208,DRUMMOND CASTLE,drummond-castle,perthshire-in-tayside-region,Met Office,56.338,-3.877,113,1970,2024\n', '00209,TUMMEL BRIDGE,tummel-bridge,perthshire-in-tayside-region,Met Office,56.706,-4.011,148,1984,1992\n', '00211,GLENEAGLES,gleneagles,perthshire-in-tayside-region,Met Office,56.281,-3.749,152,1964,1976\n', '00212,STRATHALLAN AIRFIELD,strathal

In [85]:
for i, line in enumerate(meta_data_lines):
    if line.strip() == 'data':
        x = i


meta_data_pd = pd.read_csv('midas-open_uk-daily-temperature-obs_dv-202507_station-metadata.csv', skiprows=x + 1)

print(meta_data_pd.head())

  src_id station_name station_file_name historic_county   authority  \
0  00001        FOULA             foula        shetland  Met Office
1  00003    FAIR ISLE         fair-isle        shetland  Met Office
2  00004     SUMBURGH          sumburgh        shetland  Met Office
3  00005     HAMNAVOE          hamnavoe        shetland  Met Office
4  00006      SCATSTA           scatsta        shetland  Met Office

   station_latitude  station_longitude  station_elevation  first_year  \
0            60.154             -2.074               22.0      1985.0
1            59.526             -1.630               57.0      1974.0
2            59.879             -1.299                7.0      1978.0
3            60.104             -1.333               21.0      1962.0
4            60.439             -1.308               15.0      1979.0

   last_year
0     2003.0
1     2024.0
2     1996.0
3     1973.0
4     1980.0

In [86]:
print(len(meta_data_pd))

1638

In [87]:
print(meta_data_pd.columns.to_list())

['src_id', 'station_name', 'station_file_name', 'historic_county', 'authority', 'station_latitude', 'station_longitude', 'station_elevation', 'first_year', 'last_year']

In [92]:
meta_data_pd.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1638 entries, 0 to 1637
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   src_id             1638 non-null   object
 1   station_name       1637 non-null   object
 2   station_file_name  1637 non-null   object
 3   historic_county    1637 non-null   object
 4   authority          1637 non-null   object
 5   station_latitude   1637 non-null   float64
 6   station_longitude  1637 non-null   float64
 7   station_elevation  1637 non-null   float64
 8   first_year         1637 non-null   float64
 9   last_year          1637 non-null   float64
dtypes: float64(5), object(5)
memory usage: 128.1+ KB

In [96]:
active_stations = meta_data_pd[(meta_data_pd['last_year'] >= 2024) & (meta_data_pd['first_year'] >= 1960)]

In [97]:
len(active_stations)

285

In [103]:
def get_file_url(county, src_id, station_file_name, year):
    base_url = f'https://dap.ceda.ac.uk/badc/ukmo-midas-open/data/uk-daily-temperature-obs/dataset-version-202507/{county}/'
    directory_path = f'{src_id}_{station_file_name}/qc-version-1/'
    filename = f"midas-open_uk-daily-temperature-obs_dv-202507_{county}_{src_id}_{station_file_name}_qcv-1_{year}.csv"

    return base_url + directory_path + filename

In [115]:
active_stations.head(1)

,src_id,station_name,station_file_name,historic_county,authority,station_latitude,station_longitude,station_elevation,first_year,last_year
1,00003,FAIR ISLE,fair-isle,shetland,Met Office,59.526,-1.63,57.0,1974.0,2024.0

In [118]:
get_file_url('shetland', src_id="00003", station_file_name='fair-isle', year='1974')

'https://dap.ceda.ac.uk/badc/ukmo-midas-open/data/uk-daily-temperature-obs/dataset-version-202507/shetland/00003_fair-isle/qc-version-1/midas-open_uk-daily-temperature-obs_dv-202507_shetland_00003_fair-isle_qcv-1_1974.csv'

In [146]:
with open("/Users/shakurahmad/PythonProjects/epoch/ingestion/midas-open_uk-daily-temperature-obs_dv-202507_shetland_00003_fair-isle_qcv-1_1974.csv", "r") as f:
    file_lines = f.readlines()

first_row = None

for idx, line in enumerate(file_lines):
    if line.strip() == 'data':
        first_row = idx




data_df = pd.read_csv("midas-open_uk-daily-temperature-obs_dv-202507_shetland_00003_fair-isle_qcv-1_1974.csv", skiprows=first_row+1)
data_df = data_df[data_df['ob_end_time'] != 'end data']
observation_cols = ['src_id', 'ob_end_time', 'max_air_temp', 'min_air_temp']

data_df = data_df[observation_cols]



data_df_filtered = data_df.groupby([pd.to_datetime(data_df['ob_end_time']).dt.date, 'src_id']).agg({'max_air_temp' : 'max', 'min_air_temp' : 'min'}).reset_index()

data_df_filtered

    ob_end_time  src_id  max_air_temp  min_air_temp
0    1974-04-01     3.0           7.8           6.2
1    1974-04-02     3.0           7.4           6.0
2    1974-04-03     3.0           8.8           4.6
3    1974-04-04     3.0           5.9           3.9
4    1974-04-05     3.0           5.2           3.3
..          ...     ...           ...           ...
270  1974-12-27     3.0           7.9           2.4
271  1974-12-28     3.0           8.4           5.8
272  1974-12-29     3.0           7.0           2.3
273  1974-12-30     3.0           7.6           3.2
274  1974-12-31     3.0          10.2           5.1

[275 rows x 4 columns]

In [155]:
with open("/Users/shakurahmad/PythonProjects/epoch/ingestion/midas-open_uk-daily-rain-obs_dv-202507_station-metadata.csv", 'r') as f:
    rain_lines = f.readlines()

start_row = None
for index, line in enumerate(rain_lines):
    if line.strip() == 'data':
        start_row = index

rain_df = pd.read_csv("/Users/shakurahmad/PythonProjects/epoch/ingestion/midas-open_uk-daily-rain-obs_dv-202507_station-metadata.csv", skiprows=start_row+1)
rain_df = rain_df[rain_df['src_id'] != 'end data']
rain_df = rain_df[(rain_df['first_year'] >= 1960) & (rain_df['last_year'] >= 2024)]
rain_df

,src_id,station_name,station_file_name,historic_county,authority,station_latitude,station_longitude,station_elevation,first_year,last_year
10,00019,RACKWICK,rackwick,orkney,Met Office,58.873,-3.387,18.0,1987.0,2024.0
37,00050,STRATHY EAST,strathy-east,sutherland,Met Office,58.561,-3.992,68.0,1987.0,2024.0
45,00060,POOLEWE,poolewe,ross-and-cromarty,Met Office,57.775,-5.598,6.0,1961.0,2024.0
53,00068,KNOCKANROCK,knockanrock,ross-and-cromarty,Met Office,58.031,-5.072,244.0,1967.0,2024.0
54,00069,CLUANIE INN,cluanie-inn,ross-and-cromarty,Met Office,57.156,-5.181,223.0,1961.0,2024.0
...,...,...,...,...,...,...,...,...,...,...
13334,62329,WOOTTON ST LAWRENCE,wootton-st-lawrence,hampshire,Environment Agency,51.273,-1.153,130.0,2024.0,2024.0
13335,62334,HAVERING BOWER,havering-bower,hertfordshire,Environment Agency,51.620,0.169,59.0,2024.0,2024.0
13336,62336,ALLENBY,allenby,hertfordshire,Environment Agency,51.528,-0.369,42.0,2024.0,2024.0
13337,62337,LUXBOROUGH LANE,luxborough-lane,hertfordshire,Environment Agency,51.615,0.055,15.0,2024.0,2024.0
13338,62342,NELSON GOLF CLUB,nelson-golf-club,west-yorkshire,Environment Agency,53.822,-2.209,270.0,2024.0,2024.0

In [158]:
with open("/Users/shakurahmad/Downloads/midas-open_uk-daily-rain-obs_dv-202507_aberdeenshire_00144_corgarff-castle-lodge_qcv-1_1972.csv", 'r') as f:
    rain_ab_lines = f.readlines()

start_row = None
for index, line in enumerate(rain_ab_lines):
    if line.strip() == 'data':
        start_row = index

rain_ab_df = pd.read_csv("/Users/shakurahmad/Downloads/midas-open_uk-daily-rain-obs_dv-202507_aberdeenshire_00144_corgarff-castle-lodge_qcv-1_1972.csv", skiprows=start_row+1)
rain_ab_df = rain_ab_df[rain_ab_df['src_id'] != 'end data']
rain_ab_df.columns

Index(['ob_date', 'id', 'id_type', 'version_num', 'met_domain_name',
       'ob_end_ctime', 'ob_day_cnt', 'src_id', 'rec_st_ind', 'prcp_amt',
       'ob_day_cnt_q', 'prcp_amt_q', 'prcp_amt_j', 'meto_stmp_time',
       'midas_stmp_etime'],
      dtype='object')